all: | relate geva 

geva: 
	git clone https://github.com/pkalbers/geva.git 
	cd geva && make

relate:
	wget https://myersgroup.github.io/relate/download/relate_v1.0.17_x86_64_dynamic.tgz
	tar -xzf relate_v1.0.17_x86_64_dynamic.tgz
	mv relate_v1.0.17_x86_64_dynamic relate

